In [30]:

import pandas as pd 
import numpy as np

In [209]:
combinedFile = '/Users/swethakolalapudi/Desktop/Reg_Data/PricesHistorical3.csv'

data=pd.read_csv(combinedFile ,sep=",")
data.head()

Date        AAPL        GOOG        VLO         CVX        XOM  \
0  03/01/2017  121.950000  823.310000  67.310000  113.790000  85.510000   
1  01/12/2016  115.320023  771.820007  67.611183  116.584061  89.442131   
2  01/11/2016  110.042900  758.039978  60.921318  110.502274  86.508957   
3  03/10/2016  112.472404  784.539978  58.081470  102.728424  81.840340   
4  01/09/2016  111.987015  777.289978  51.963501  100.933739  85.730011   

          GSPC    FVX  
0  2294.690000  1.941  
1  2238.830078  1.934  
2  2198.810059  1.834  
3  2126.149902  1.313  
4  2168.270020  1.156

In [210]:
data['Date'] = pd.to_datetime(data['Date'], format='%d/%m/%Y')
data.head()

Date        AAPL        GOOG        VLO         CVX        XOM  \
0 2017-01-03  121.950000  823.310000  67.310000  113.790000  85.510000   
1 2016-12-01  115.320023  771.820007  67.611183  116.584061  89.442131   
2 2016-11-01  110.042900  758.039978  60.921318  110.502274  86.508957   
3 2016-10-03  112.472404  784.539978  58.081470  102.728424  81.840340   
4 2016-09-01  111.987015  777.289978  51.963501  100.933739  85.730011   

          GSPC    FVX  
0  2294.690000  1.941  
1  2238.830078  1.934  
2  2198.810059  1.834  
3  2126.149902  1.313  
4  2168.270020  1.156

In [211]:
data = data.sort_values(['Date'], ascending=[True])
data.head()

Date       AAPL        GOOG        VLO        CVX        XOM  \
120 2007-01-03  11.107141  250.499939  39.694862  50.777351  56.765919   
119 2007-02-01  10.962033  224.500885  42.169876  48.082939  55.145882   
118 2007-03-01  12.037377  228.851547  47.263386  51.900383  58.046268   
117 2007-04-02  12.930043  235.454956  51.470112  54.588032  61.069752   
116 2007-05-01  15.701322  248.706726  54.776485  57.598267  64.261772   

            GSPC    FVX  
120  1438.239990  4.819  
119  1406.819946  4.503  
118  1420.859985  4.537  
117  1482.369995  4.516  
116  1530.619995  4.853

In [212]:
returns = data[[key for key in dict(data.dtypes) if dict(data.dtypes)[key] in ['float64', 'int64']]].pct_change()
returns = data[["AAPL","GOOG","XOM","CVX","VLO","GSPC","FVX"]].pct_change()

In [213]:
returns.head()

AAPL      GOOG       XOM       CVX       VLO      GSPC       FVX
120       NaN       NaN       NaN       NaN       NaN       NaN       NaN
119 -0.013064 -0.103789 -0.028539 -0.053063  0.062351 -0.021846 -0.065574
118  0.098097  0.019379  0.052595  0.079393  0.120786  0.009980  0.007551
117  0.074158  0.028855  0.052087  0.051785  0.089006  0.043291 -0.004629
116  0.214329  0.056282  0.052268  0.055145  0.064239  0.032549  0.074624

In [214]:
returns = returns[1:]

In [215]:
yVars = returns[["GOOG","XOM","CVX","VLO","GSPC","FVX"]]

In [216]:
stdYVars = (yVars - yVars .mean()) / (yVars .std())

In [217]:
yVars .cov()
yVars .corr()

GOOG       XOM       CVX       VLO      GSPC       FVX
GOOG  1.000000  0.296639  0.358988  0.397233  0.566361  0.247775
XOM   0.296639  1.000000  0.794910  0.343255  0.549284  0.190377
CVX   0.358988  0.794910  1.000000  0.401616  0.643503  0.236250
VLO   0.397233  0.343255  0.401616  1.000000  0.585980  0.290939
GSPC  0.566361  0.549284  0.643503  0.585980  1.000000  0.271478
FVX   0.247775  0.190377  0.236250  0.290939  0.271478  1.000000

In [218]:
eig_val, eig_vec = np.linalg.eig(stdYVars.cov())

In [219]:
eig_pairs = [(np.abs(eig_val[i]), eig_vec[:,i]) for i in range(len(eig_val))]

In [220]:
eig_pairs.sort(key=lambda x: x[0], reverse=True)

In [221]:
eig_pairs

[(3.1459527934123352,
  array([-0.36888058, -0.43483546, -0.46995619, -0.39270158, -0.48817562,
         -0.24790412])),
 (0.97887501264048482,
  array([-0.33713512,  0.49740615,  0.40786685, -0.30141047, -0.02499783,
         -0.61733176])),
 (0.78520516166320942,
  array([-0.49720335,  0.25617574,  0.20001077, -0.2357954 , -0.22831947,
          0.73445848])),
 (0.59531868678877364,
  array([-0.62527658, -0.06762299, -0.05873725,  0.76388678,  0.03893528,
         -0.12636179])),
 (0.30347275530593398,
  array([-0.33190136, -0.35822719,  0.01880332, -0.33681084,  0.80396233,
          0.03693549])),
 (0.19117559018926478,
  array([ 0.04389248, -0.60413545,  0.75430622,  0.04871521, -0.24710021,
         -0.02615804]))]

In [222]:
eVector1 = eig_vec[:,0]
eVector2 = eig_vec[:,1]
eVector3 = eig_vec[:,2]

In [223]:
pca1 = np.dot(stdYVars,eVector1.T).T
pca1

array([ 1.53322382, -1.50234213, -1.55256284, -1.62395966, -0.09663583,
        0.93823144, -0.27957545, -1.76541527, -0.90111747,  1.92923911,
       -0.89940503,  4.27199975,  1.06393377,  1.56796362, -3.89748445,
       -0.21594336,  2.44982842,  3.51800973, -0.07280383,  3.01245524,
        5.02883861,  1.42701908,  0.18607333,  0.77354152,  4.09781747,
       -1.1351224 , -1.77894402, -1.89842092,  0.93143237, -1.45166034,
       -0.40378792, -0.51508386, -0.74121007, -0.83968222, -0.00657368,
        2.17555611, -0.05155364, -2.04455783, -0.38566707,  3.70633122,
        2.77196112, -1.91425566,  1.79329853, -2.93979734, -1.6982203 ,
       -0.41233337, -3.54633664, -1.61470643, -2.16693848,  0.05409101,
        0.06988946,  1.56911567,  1.23499044,  0.16911815,  3.1461962 ,
        2.71277462, -4.82895256,  0.46055438, -0.53776002,  0.31895367,
       -1.8388621 , -0.63698897,  1.20522854,  3.24608238, -2.23642738,
       -0.93140947, -1.19001369, -1.34642586,  1.44909472,  0.44

In [224]:
pca2 = np.dot(stdYVars,eVector2.T).T

In [225]:
pca3 = np.dot(stdYVars,eVector3.T).T


In [226]:
xData = np.vstack([pca1,pca2,pca3]).T
xData

array([[ 1.53322382, -0.15235316, -0.00597316],
       [-1.50234213,  0.64944468,  0.22240361],
       [-1.55256284,  0.53486609, -0.09269946],
       [-1.62395966,  0.19897512,  0.25387167],
       [-0.09663583,  0.08380966,  0.12138663],
       [ 0.93823144,  0.88625416,  0.36105683],
       [-0.27957545,  0.55970201, -0.3110369 ],
       [-1.76541527,  0.9469021 , -0.04799421],
       [-0.90111747, -1.30000175, -1.76595244],
       [ 1.92923911,  0.51633915, -0.57910702],
       [-0.89940503,  0.72883603,  0.49655574],
       [ 4.27199975,  0.29691939,  0.08286062],
       [ 1.06393377,  1.73577946,  0.98328888],
       [ 1.56796362,  0.34264528,  0.51586391],
       [-3.89748445, -0.24374951,  0.12102469],
       [-0.21594336, -0.90785422,  0.2895987 ],
       [ 2.44982842,  0.97985397,  1.38296334],
       [ 3.51800973, -0.92771328,  0.02659779],
       [-0.07280383,  0.36656226, -0.14165991],
       [ 3.01245524,  0.46266179,  1.13567114],
       [ 5.02883861,  0.47602746,  1.398

In [227]:
stdReturns = (returns["AAPL"] - returns["AAPL"].mean()) / (returns["AAPL"].std())

In [228]:
yData = (returns["AAPL"] - returns["AAPL"].mean()) / (returns["AAPL"].std())

In [229]:
import statsmodels.api as sm
import matplotlib.pyplot as plt
import numpy as np
from sklearn import linear_model

In [230]:
goodAaplModel = linear_model.LinearRegression()

In [231]:
goodAaplModel .fit(xData,yData)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [232]:
goodAaplModel .score(xData,yData)

0.37007268576699703

In [233]:
model = sm.OLS(yData, xData)

In [202]:
results = model.fit()

In [203]:
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                   AAPL   R-squared:                       0.370
Model:                            OLS   Adj. R-squared:                  0.354
Method:                 Least Squares   F-statistic:                     22.91
Date:                Sun, 26 Feb 2017   Prob (F-statistic):           9.72e-12
Time:                        07:18:02   Log-Likelihood:                -142.04
No. Observations:                 120   AIC:                             290.1
Df Residuals:                     117   BIC:                             298.4
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
x1            -0.3069      0.041     -7.419      0.0